apiVersion: v1
data:
  context: "argocdUrl: \n"
  service.webhook.logstash: |
    url: http://logstash-logstash.default.svc.cluster.local:5043
    headers:
    - name: Content-Type
      value: application/json
  service.email: |
    host: mailhog.monitoring.svc.cluster.local
    port: 1025
    from: argocd-alerts@cloudogu.com
  service.slack: |
    token: $slack-token
  subscriptions: |
    - recipients:
      - email:alerts@cloudogu.com
      - webhook:logstash
      triggers:
      - on-health-degraded
      - on-sync-failed
  template.app-deployed: |
    email:
      subject: New version of an application {{.app.metadata.name}} is up and running.
    message: |
      Application {{.app.metadata.name}} is now running new version of deployments manifests.
  template.app-health-degraded: |
    email:
      subject: Application {{.app.metadata.name}} has degraded.
    message: |
      Application {{.app.metadata.name}} has degraded.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
  template.send-logstash: |
    webhook:
      logstash:
        method: POST
        body: |
          {
            "Status": "Sync failed",
            "Application": {{.app.metadata.name}}
          }

  template.app-sync-failed: |
    email:
      subject: Failed to sync application {{.app.metadata.name}}.
    message: |
      The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  template.app-sync-running: |
    email:
      subject: Start syncing application {{.app.metadata.name}}.
    message: |
      The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationState.startedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  template.app-sync-status-longer-10s: |
    email:
      subject: Application {{.app.metadata.name}} is too long in sync status.
    message: |
      The Application {{.app.metadata.name}} is now longer than 10 seconds in sync status. This may be because one of its resources resides in a SyncFailed status.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  template.app-sync-status-unknown: |
    email:
      subject: Application {{.app.metadata.name}} sync status is 'Unknown'
    message: |
      Application {{.app.metadata.name}} sync is 'Unknown'.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
      {{range $c := .app.status.conditions}}
          * {{$c.message}}
      {{end}}
  template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
      - app-deployed
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-running: |
    - description: Application is being synced
      send:
      - app-sync-running
      when: app.status.operationState.phase in ['Running']
  trigger.on-sync-status-longer-10s: |
    - description: Application syncing is longer than 10 seconds
      send:
      - app-sync-status-longer-10s
      when: app.status.operationState.phase in ['Running'] and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Seconds() >= 10
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send:
      - app-sync-status-unknown
      when: app.status.sync.status == 'Unknown'
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"context":"argocdUrl: \n","service.email":"host: mailhog.monitoring.svc.cluster.local\nport: 1025\nfrom: argocd-alerts@cloudogu.com\n","service.slack":"token: $slack-token\n","subscriptions":"- recipients:\n  - email:alerts@cloudogu.com\n  triggers:\n  - on-health-degraded\n  - on-sync-failed\n","template.app-deployed":"email:\n  subject: New version of an application {{.app.metadata.name}} is up and running.\nmessage: |\n  Application {{.app.metadata.name}} is now running new version of deployments manifests.\n","template.app-health-degraded":"email:\n  subject: Application {{.app.metadata.name}} has degraded.\nmessage: |\n  Application {{.app.metadata.name}} has degraded.\n  Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.\n","template.app-sync-failed":"email:\n  subject: Failed to sync application {{.app.metadata.name}}.\nmessage: |\n  The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}\n  Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .\n","template.app-sync-running":"email:\n  subject: Start syncing application {{.app.metadata.name}}.\nmessage: |\n  The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationState.startedAt}}.\n  Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .\n","template.app-sync-status-longer-10s":"email:\n  subject: Application {{.app.metadata.name}} is too long in sync status.\nmessage: |\n  The Application {{.app.metadata.name}} is now longer than 10 seconds in sync status. This may be because one of its resources resides in a SyncFailed status.\n  Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .\n","template.app-sync-status-unknown":"email:\n  subject: Application {{.app.metadata.name}} sync status is 'Unknown'\nmessage: |\n  Application {{.app.metadata.name}} sync is 'Unknown'.\n  Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.\n  {{range $c := .app.status.conditions}}\n      * {{$c.message}}\n  {{end}}\n","template.app-sync-succeeded":"email:\n  subject: Application {{.app.metadata.name}} has been successfully synced.\nmessage: |\n  Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.\n  Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .\n","trigger.on-deployed":"- description: Application is synced and healthy. Triggered once per commit.\n  oncePer: app.status.sync.revision\n  send:\n  - app-deployed\n  when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'\n","trigger.on-health-degraded":"- description: Application has degraded\n  send:\n  - app-health-degraded\n  when: app.status.health.status == 'Degraded'\n","trigger.on-sync-failed":"- description: Application syncing has failed\n  send:\n  - app-sync-failed\n  when: app.status.operationState.phase in ['Error', 'Failed']\n","trigger.on-sync-running":"- description: Application is being synced\n  send:\n  - app-sync-running\n  when: app.status.operationState.phase in ['Running']\n","trigger.on-sync-status-longer-10s":"- description: Application syncing is longer than 10 seconds\n  send:\n  - app-sync-status-longer-10s\n  when: app.status.operationState.phase in ['Running'] and time.Now().Sub(time.Parse(app.status.operationState.startedAt)).Seconds() \u003e= 10\n","trigger.on-sync-status-unknown":"- description: Application status is 'Unknown'\n  send:\n  - app-sync-status-unknown\n  when: app.status.sync.status == 'Unknown'\n","trigger.on-sync-succeeded":"- description: Application syncing has succeeded\n  send:\n  - app-sync-succeeded\n  when: app.status.operationState.phase in ['Succeeded']\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"argocd-notifications","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"argocd-notifications","app.kubernetes.io/version":"1.1.1","argocd.argoproj.io/instance":"argocd-notifications","helm.sh/chart":"argocd-notifications-1.5.1"},"name":"argocd-notifications-cm","namespace":"argocd"}}
  creationTimestamp: "2022-04-07T09:02:29Z"
  labels:
    app.kubernetes.io/instance: argocd-notifications
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/version: 1.1.1
    argocd.argoproj.io/instance: argocd-notifications
    helm.sh/chart: argocd-notifications-1.5.1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:context: {}
        f:service.email: {}
        f:service.slack: {}
        f:subscriptions: {}
        f:template.app-deployed: {}
        f:template.app-health-degraded: {}
        f:template.app-sync-failed: {}
        f:template.app-sync-running: {}
        f:template.app-sync-status-longer-10s: {}
        f:template.app-sync-status-unknown: {}
        f:template.app-sync-succeeded: {}
        f:trigger.on-deployed: {}
        f:trigger.on-health-degraded: {}
        f:trigger.on-sync-failed: {}
        f:trigger.on-sync-running: {}
        f:trigger.on-sync-status-longer-10s: {}
        f:trigger.on-sync-status-unknown: {}
        f:trigger.on-sync-succeeded: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:argocd.argoproj.io/instance: {}
          f:helm.sh/chart: {}
    manager: argocd-application-controller
    operation: Update
    time: "2022-04-07T09:02:29Z"
  name: argocd-notifications-cm
  namespace: argocd
