apiVersion: v1
kind: Service
metadata:
  name: sampleservice
  labels:
    app: sampleapp
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx